<?php


$countries = array(
    array('id' => 1, 'title' => 'Afghanistan'),
    array('id' => 1, 'title' => 'Albania'),
    array('id' => 1, 'title' => 'Algeria'),
    array('id' => 1, 'title' => 'Andorra'),
    array('id' => 1, 'title' => 'Angola'),
    array('id' => 1, 'title' => 'Antigua & Deps'),
    array('id' => 1, 'title' => 'Argentina'),
    array('id' => 1, 'title' => 'Armenia'),
    array('id' => 1, 'title' => 'Australia'),
    array('id' => 1, 'title' => 'Austria'),
    array('id' => 1, 'title' => 'Azerbaijan'),
    array('id' => 1, 'title' => 'Bahamas'),
    array('id' => 1, 'title' => 'Bahrain'),
    array('id' => 1, 'title' => 'Bangladesh'),
    array('id' => 1, 'title' => 'Barbados'),
    array('id' => 1, 'title' => 'Belarus'),
    array('id' => 1, 'title' => 'Belgium'),
    array('id' => 1, 'title' => 'Belize'),
    array('id' => 1, 'title' => 'Benin'),
    array('id' => 1, 'title' => 'Bhutan'),
    array('id' => 1, 'title' => 'Bolivia'),
    array('id' => 1, 'title' => 'Bosnia Herzegovina'),
    array('id' => 1, 'title' => 'Botswana'),
    array('id' => 1, 'title' => 'Brazil'),
    array('id' => 1, 'title' => 'Brunei'),
    array('id' => 1, 'title' => 'Bulgaria'),
    array('id' => 1, 'title' => 'Burkina'),
    array('id' => 1, 'title' => 'Burundi'),
    array('id' => 1, 'title' => 'Cambodia'),
    array('id' => 1, 'title' => 'Cameroon'),
    array('id' => 1, 'title' => 'Canada'),
    array('id' => 1, 'title' => 'Cape Verde'),
    array('id' => 1, 'title' => 'Central African Rep'),
    array('id' => 1, 'title' => 'Chad'),
    array('id' => 1, 'title' => 'Chile'),
    array('id' => 1, 'title' => 'China'),
    array('id' => 1, 'title' => 'Colombia'),
    array('id' => 1, 'title' => 'Comoros'),
    array('id' => 1, 'title' => 'Congo'),
    array('id' => 1, 'title' => 'Congo {Democratic Rep}'),
    array('id' => 1, 'title' => 'Costa Rica'),
    array('id' => 1, 'title' => 'Croatia'),
    array('id' => 1, 'title' => 'Cuba'),
    array('id' => 1, 'title' => 'Cyprus'),
    array('id' => 1, 'title' => 'Czech Republic'),
    array('id' => 1, 'title' => 'Denmark'),
    array('id' => 1, 'title' => 'Djibouti'),
    array('id' => 1, 'title' => 'Dominica'),
    array('id' => 1, 'title' => 'Dominican Republic'),
    array('id' => 1, 'title' => 'East Timor'),
    array('id' => 1, 'title' => 'Ecuador'),
    array('id' => 1, 'title' => 'Egypt'),
    array('id' => 1, 'title' => 'El Salvador'),
    array('id' => 1, 'title' => 'Equatorial Guinea'),
    array('id' => 1, 'title' => 'Eritrea'),
    array('id' => 1, 'title' => 'Estonia'),
    array('id' => 1, 'title' => 'Ethiopia'),
    array('id' => 1, 'title' => 'Fiji'),
    array('id' => 1, 'title' => 'Finland'),
    array('id' => 1, 'title' => 'France'),
    array('id' => 1, 'title' => 'Gabon'),
    array('id' => 1, 'title' => 'Gambia'),
    array('id' => 1, 'title' => 'Georgia'),
    array('id' => 1, 'title' => 'Germany'),
    array('id' => 1, 'title' => 'Ghana'),
    array('id' => 1, 'title' => 'Greece'),
    array('id' => 1, 'title' => 'Grenada'),
    array('id' => 1, 'title' => 'Guatemala'),
    array('id' => 1, 'title' => 'Guinea'),
    array('id' => 1, 'title' => 'Guinea-Bissau'),
    array('id' => 1, 'title' => 'Guyana'),
    array('id' => 1, 'title' => 'Haiti'),
    array('id' => 1, 'title' => 'Honduras'),
    array('id' => 1, 'title' => 'Hungary'),
    array('id' => 1, 'title' => 'Iceland'),
    array('id' => 1, 'title' => 'India'),
    array('id' => 1, 'title' => 'Indonesia'),
    array('id' => 1, 'title' => 'Iran'),
    array('id' => 1, 'title' => 'Iraq'),
    array('id' => 1, 'title' => 'Ireland {Republic}'),
    array('id' => 1, 'title' => 'Israel'),
    array('id' => 1, 'title' => 'Italy'),
    array('id' => 1, 'title' => 'Ivory Coast'),
    array('id' => 1, 'title' => 'Jamaica'),
    array('id' => 1, 'title' => 'Japan'),
    array('id' => 1, 'title' => 'Jordan'),
    array('id' => 1, 'title' => 'Kazakhstan'),
    array('id' => 1, 'title' => 'Kenya'),
    array('id' => 1, 'title' => 'Kiribati'),
    array('id' => 1, 'title' => 'Korea North'),
    array('id' => 1, 'title' => 'Korea South'),
    array('id' => 1, 'title' => 'Kosovo'),
    array('id' => 1, 'title' => 'Kuwait'),
    array('id' => 1, 'title' => 'Kyrgyzstan'),
    array('id' => 1, 'title' => 'Laos'),
    array('id' => 1, 'title' => 'Latvia'),
    array('id' => 1, 'title' => 'Lebanon'),
    array('id' => 1, 'title' => 'Lesotho'),
    array('id' => 1, 'title' => 'Liberia'),
    array('id' => 1, 'title' => 'Libya'),
    array('id' => 1, 'title' => 'Liechtenstein'),
    array('id' => 1, 'title' => 'Lithuania'),
    array('id' => 1, 'title' => 'Luxembourg'),
    array('id' => 1, 'title' => 'Macedonia'),
    array('id' => 1, 'title' => 'Madagascar'),
    array('id' => 1, 'title' => 'Malawi'),
    array('id' => 1, 'title' => 'Malaysia'),
    array('id' => 1, 'title' => 'Maldives'),
    array('id' => 1, 'title' => 'Mali'),
    array('id' => 1, 'title' => 'Malta'),
    array('id' => 1, 'title' => 'Marshall Islands'),
    array('id' => 1, 'title' => 'Mauritania'),
    array('id' => 1, 'title' => 'Mauritius'),
    array('id' => 1, 'title' => 'Mexico'),
    array('id' => 1, 'title' => 'Micronesia'),
    array('id' => 1, 'title' => 'Moldova'),
    array('id' => 1, 'title' => 'Monaco'),
    array('id' => 1, 'title' => 'Mongolia'),
    array('id' => 1, 'title' => 'Montenegro'),
    array('id' => 1, 'title' => 'Morocco'),
    array('id' => 1, 'title' => 'Mozambique'),
    array('id' => 1, 'title' => 'Myanmar, {Burma}'),
    array('id' => 1, 'title' => 'Namibia'),
    array('id' => 1, 'title' => 'Nauru'),
    array('id' => 1, 'title' => 'Nepal'),
    array('id' => 1, 'title' => 'Netherlands'),
    array('id' => 1, 'title' => 'New Zealand'),
    array('id' => 1, 'title' => 'Nicaragua'),
    array('id' => 1, 'title' => 'Niger'),
    array('id' => 1, 'title' => 'Nigeria'),
    array('id' => 1, 'title' => 'Norway'),
    array('id' => 1, 'title' => 'Oman'),
    array('id' => 1, 'title' => 'Pakistan'),
    array('id' => 1, 'title' => 'Palau'),
    array('id' => 1, 'title' => 'Panama'),
    array('id' => 1, 'title' => 'Papua New Guinea'),
    array('id' => 1, 'title' => 'Paraguay'),
    array('id' => 1, 'title' => 'Peru'),
    array('id' => 1, 'title' => 'Philippines'),
    array('id' => 1, 'title' => 'Poland'),
    array('id' => 1, 'title' => 'Portugal'),
    array('id' => 1, 'title' => 'Qatar'),
    array('id' => 1, 'title' => 'Romania'),
    array('id' => 1, 'title' => 'Russian Federation'),
    array('id' => 1, 'title' => 'Rwanda'),
    array('id' => 1, 'title' => 'St Kitts & Nevis'),
    array('id' => 1, 'title' => 'St Lucia'),
    array('id' => 1, 'title' => 'Saint Vincent & the Grenadines'),
    array('id' => 1, 'title' => 'Samoa'),
    array('id' => 1, 'title' => 'San Marino'),
    array('id' => 1, 'title' => 'Sao Tome & Principe'),
    array('id' => 1, 'title' => 'Saudi Arabia'),
    array('id' => 1, 'title' => 'Senegal'),
    array('id' => 1, 'title' => 'Serbia'),
    array('id' => 1, 'title' => 'Seychelles'),
    array('id' => 1, 'title' => 'Sierra Leone'),
    array('id' => 1, 'title' => 'Singapore'),
    array('id' => 1, 'title' => 'Slovakia'),
    array('id' => 1, 'title' => 'Slovenia'),
    array('id' => 1, 'title' => 'Solomon Islands'),
    array('id' => 1, 'title' => 'Somalia'),
    array('id' => 1, 'title' => 'South Africa'),
    array('id' => 1, 'title' => 'South Sudan'),
    array('id' => 1, 'title' => 'Spain'),
    array('id' => 1, 'title' => 'Sri Lanka'),
    array('id' => 1, 'title' => 'Sudan'),
    array('id' => 1, 'title' => 'Suriname'),
    array('id' => 1, 'title' => 'Swaziland'),
    array('id' => 1, 'title' => 'Sweden'),
    array('id' => 1, 'title' => 'Switzerland'),
    array('id' => 1, 'title' => 'Syria'),
    array('id' => 1, 'title' => 'Taiwan'),
    array('id' => 1, 'title' => 'Tajikistan'),
    array('id' => 1, 'title' => 'Tanzania'),
    array('id' => 1, 'title' => 'Thailand'),
    array('id' => 1, 'title' => 'Togo'),
    array('id' => 1, 'title' => 'Tonga'),
    array('id' => 1, 'title' => 'Trinidad & Tobago'),
    array('id' => 1, 'title' => 'Tunisia'),
    array('id' => 1, 'title' => 'Turkey'),
    array('id' => 1, 'title' => 'Turkmenistan'),
    array('id' => 1, 'title' => 'Tuvalu'),
    array('id' => 1, 'title' => 'Uganda'),
    array('id' => 1, 'title' => 'Ukraine'),
    array('id' => 1, 'title' => 'United Arab Emirates'),
    array('id' => 1, 'title' => 'United Kingdom'),
    array('id' => 1, 'title' => 'United States'),
    array('id' => 1, 'title' => 'Uruguay'),
    array('id' => 1, 'title' => 'Uzbekistan'),
    array('id' => 1, 'title' => 'Vanuatu'),
    array('id' => 1, 'title' => 'Vatican City'),
    array('id' => 1, 'title' => 'Venezuela'),
    array('id' => 1, 'title' => 'Vietnam'),
    array('id' => 1, 'title' => 'Yemen'),
    array('id' => 1, 'title' => 'Zambia'),
    array('id' => 1, 'title' => 'Zimbabwe')
);

if (isset($_POST['query'])) {
    $ret = array();
    $countFoundRecords = 0;
    for ($i = 0, $count = count($countries); $i < $count; $i++) {
        if (stristr($countries[$i]['title'], $_POST['query'])) {
            $ret[] = $countries[$i];
            $countFoundRecords++;
            if ($countFoundRecords > $_POST['maxDisplayed']) {
                break;
            }
        }
    }

    $data = array('success' => true, 'message' => '', 'data' => $ret);
    echo utf8_encode(json_encode($data));
}

if (isset($_POST['getAllCountries'])) {
    $data = array('success' => true, 'message' => '', 'data' => $countries);
    echo utf8_encode(json_encode($data));
}

if (isset($_POST['getCountry'])) {
    // $_POST['getCountry'] represents a record. If only value is present, it will
    // look like this: $_POST['getCountry']['id'] = 1 where 1 is the id
    $data = array('success' => true, 'message' => '', 'data' => array('id' => 1, 'title' => 'United Kingdom'));
    echo utf8_encode(json_encode($data));

}