<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'author' => '/ludodDB/examples/mod_rewrite/Author.php',
                'book' => '/ludodDB/examples/mod_rewrite/Book.php',
                'bookauthor' => '/ludodDB/examples/mod_rewrite/BookAuthor.php',
                'bookauthors' => '/ludodDB/examples/mod_rewrite/BookAuthors.php',
                'chessprogressbar' => '/php-progress-bar/progress-bar.class.php',
                'democities' => '/ludodDB/examples/cities/DemoCities.php',
                'democity' => '/ludodDB/examples/cities/DemoCity.php',
                'democountries' => '/ludodDB/examples/cities/DemoCountries.php',
                'democountry' => '/ludodDB/examples/cities/DemoCountry.php',
                'demostate' => '/ludodDB/examples/cities/DemoState.php',
                'demostates' => '/ludodDB/examples/cities/DemoStates.php',
                'fileupload' => '/resources/FileUpload.php',
                'gridwithpaging' => '/resources/GridWithPaging.php',
                'ludodb' => '/ludodDB/LudoDB.php',
                'ludodbadapter' => '/ludodDB/LudoDBInterfaces.php',
                'ludodbcache' => '/ludodDB/LudoDBCache.php',
                'ludodbclassnotfoundexception' => '/ludodDB/LudoDBExceptions.php',
                'ludodbcollection' => '/ludodDB/LudoDBCollection.php',
                'ludodbcollectionconfigparser' => '/ludodDB/LudoDBCollectionConfigParser.php',
                'ludodbconfigparser' => '/ludodDB/LudoDBConfigParser.php',
                'ludodbconnectionexception' => '/ludodDB/LudoDBExceptions.php',
                'ludodbexception' => '/ludodDB/LudoDBExceptions.php',
                'ludodbinvalidconfigexception' => '/ludodDB/LudoDBExceptions.php',
                'ludodbinvalidserviceexception' => '/ludodDB/LudoDBExceptions.php',
                'ludodbiterator' => '/ludodDB/LudoDBIterator.php',
                'ludodbmodel' => '/ludodDB/LudoDBModel.php',
                'ludodbmysql' => '/ludodDB/LudoDBMysql.php',
                'ludodbmysqli' => '/ludodDB/LudoDBMySqlI.php',
                'ludodbobject' => '/ludodDB/LudoDBObject.php',
                'ludodbobjectnotfoundexception' => '/ludodDB/LudoDBExceptions.php',
                'ludodbpdo' => '/ludodDB/LudoDBPDO.php',
                'ludodbregistry' => '/ludodDB/LudoDBRegistry.php',
                'ludodbrequesthandler' => '/ludodDB/LudoDBRequestHandler.php',
                'ludodbservice' => '/ludodDB/LudoDBInterfaces.php',
                'ludodbservicenotimplementedexception' => '/ludodDB/LudoDBExceptions.php',
                'ludodbsql' => '/ludodDB/LudoDBSQL.php',
                'ludodbtreecollection' => '/ludodDB/LudoDBTreeCollection.php',
                'ludodbunauthorizedexception' => '/ludodDB/LudoDBExceptions.php',
                'ludodbutility' => '/ludodDB/LudoDBUtility.php',
                'user' => '/resources/User.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd