<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'author' => '/ludoDB/examples/mod_rewrite/Author.php',
                'book' => '/ludoDB/examples/mod_rewrite/Book.php',
                'bookauthor' => '/ludoDB/examples/mod_rewrite/BookAuthor.php',
                'bookauthors' => '/ludoDB/examples/mod_rewrite/BookAuthors.php',
                'chessprogressbar' => '/php-progress-bar/progress-bar.class.php',
                'countries' => '/resources/Countries.php',
                'democities' => '/ludoDB/examples/cities/DemoCities.php',
                'democity' => '/ludoDB/examples/cities/DemoCity.php',
                'democountries' => '/ludoDB/examples/cities/DemoCountries.php',
                'democountry' => '/ludoDB/examples/cities/DemoCountry.php',
                'demostate' => '/ludoDB/examples/cities/DemoState.php',
                'demostates' => '/ludoDB/examples/cities/DemoStates.php',
                'fileupload' => '/resources/FileUpload.php',
                'gridwithpaging' => '/resources/GridWithPaging.php',
                'ixhprofruns' => '/ludoDB/xhprof/xhprof_lib/utils/xhprof_runs.php',
                'ludodb' => '/ludoDB/LudoDB.php',
                'ludodbadapter' => '/ludoDB/LudoDBInterfaces.php',
                'ludodbcache' => '/ludoDB/LudoDBCache.php',
                'ludodbclassnotfoundexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbcollection' => '/ludoDB/LudoDBCollection.php',
                'ludodbcollectionconfigparser' => '/ludoDB/LudoDBCollectionConfigParser.php',
                'ludodbconfigparser' => '/ludoDB/LudoDBConfigParser.php',
                'ludodbconnectionexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbinvalidargumentsexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbinvalidconfigexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbinvalidserviceexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbiterator' => '/ludoDB/LudoDBIterator.php',
                'ludodbmodel' => '/ludoDB/LudoDBModel.php',
                'ludodbmysql' => '/ludoDB/LudoDBMysql.php',
                'ludodbmysqli' => '/ludoDB/LudoDBMySqlI.php',
                'ludodbobject' => '/ludoDB/LudoDBObject.php',
                'ludodbobjectnotfoundexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbpdo' => '/ludoDB/LudoDBPDO.php',
                'ludodbprofiling' => '/ludoDB/LudoDBProfiling.php',
                'ludodbregistry' => '/ludoDB/LudoDBRegistry.php',
                'ludodbrequesthandler' => '/ludoDB/LudoDBRequestHandler.php',
                'ludodbservice' => '/ludoDB/LudoDBInterfaces.php',
                'ludodbservicenotimplementedexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbserviceregistry' => '/ludoDB/LudoDBServiceRegistry.php',
                'ludodbsql' => '/ludoDB/LudoDBSQL.php',
                'ludodbtreecollection' => '/ludoDB/LudoDBTreeCollection.php',
                'ludodbunauthorizedexception' => '/ludoDB/LudoDBExceptions.php',
                'ludodbutility' => '/ludoDB/LudoDBUtility.php',
                'user' => '/resources/User.php',
                'xhpprofiling' => '/ludoDB/xhprof/XHPProfiling.php',
                'xhprofruns_default' => '/ludoDB/xhprof/xhprof_lib/utils/xhprof_runs.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    }
);
// @codeCoverageIgnoreEnd